import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowUp, ArrowUpDown, CheckCircle2, ChevronDown, CloudUpload, FileSpreadsheet, Filter, LineChart, PackageSearch, RefreshCw, Search, Settings2, Store, X } from "lucide-react";
import { parseBusinessFiles } from "./businessParser";
import { usePersistedState } from "./persistence";
import type { BusinessAnalysisState, BusinessBatch, BusinessCardMetrics, BusinessMallMetrics, BusinessProductFilters, BusinessProductRecord, BusinessSortField, SortDirection } from "./types";
import { formatCompact, formatCount, formatCurrency } from "./utils";

const defaultFilters = (): BusinessProductFilters => ({ search: "", publishStatus: "all", sales: "all", cardGmvMin: "", cardGmvMax: "", impressionsMin: "", impressionsMax: "", ctrMin: "", ctrMax: "", addToCartRateMin: "", addToCartRateMax: "", ctorMin: "", ctorMax: "", mallImpressionsMin: "", mallImpressionsMax: "", mallCtrMin: "", mallCtrMax: "" });
const defaultColumns: BusinessSortField[] = ["cardGmv", "skuOrders", "impressions", "clicks", "ctr", "addToCartRate", "ctor", "mallImpressions", "mallCtr"];
const optionalColumns: BusinessSortField[] = ["units", "customers", "aov", "addToCarts", "uniqueImpressions", "uniqueClicks", "uniqueCtr", "addToCartUsers", "uniqueAddToCartRate", "uniqueCtor", "mallClicks", "mallUniqueClicks", "mallCustomers", "mallCtor", "mallGmv", "mallUnits"];
const columnLabels: Record<BusinessSortField, string> = { cardGmv: "商品卡 GMV", skuOrders: "SKU订单", impressions: "曝光", clicks: "点击", ctr: "CTR", addToCartRate: "加购率", ctor: "CTOR", mallImpressions: "商城曝光", mallCtr: "商城CTR", units: "商品成交件数", customers: "预计客户数", aov: "AOV", addToCarts: "加购次数", uniqueImpressions: "去重曝光", uniqueClicks: "去重点击", uniqueCtr: "去重CTR", addToCartUsers: "已加购用户数", uniqueAddToCartRate: "去重加购率", uniqueCtor: "去重CTOR", mallClicks: "商城点击", mallUniqueClicks: "商城去重点击", mallCustomers: "商城预计客户数", mallCtor: "商城CTOR", mallGmv: "商城GMV", mallUnits: "商城成交件数" };
const cardTrendOptions = ["gmv", "skuOrders", "impressions", "clicks", "ctr", "addToCartRate", "ctor", "aov"] as const;
const mallTrendOptions = ["gmv", "impressions", "clicks", "ctr", "ctor"] as const;
const cardTrendLabels: Record<(typeof cardTrendOptions)[number], string> = { gmv: "GMV", skuOrders: "SKU订单", impressions: "曝光", clicks: "点击", ctr: "CTR", addToCartRate: "加购率", ctor: "CTOR", aov: "AOV" };
const mallTrendLabels: Record<(typeof mallTrendOptions)[number], string> = { gmv: "商城GMV", impressions: "商城曝光", clicks: "商城点击", ctr: "商城CTR", ctor: "商城CTOR" };
const initialState = (): BusinessAnalysisState => ({ batches: [], activeBatchId: null, activeTab: "overview", filters: defaultFilters(), sort: { field: null, direction: null }, visibleColumns: [], cardTrendMetrics: ["gmv", "impressions"], mallTrendMetrics: ["gmv", "impressions"] });

const parseInput = (value: string): number | null => { const parsed = Number(value); return value.trim() && Number.isFinite(parsed) ? parsed : null; };
const rate = (value: number | null) => value === null ? "—" : `${value.toFixed(value % 1 ? 2 : 0)}%`;
const amount = (value: number | null) => value === null ? "—" : formatCurrency(value);
const count = (value: number | null) => value === null ? "—" : formatCompact(value);
const isRate = (field: BusinessSortField) => ["ctr", "addToCartRate", "ctor", "uniqueCtr", "uniqueAddToCartRate", "uniqueCtor", "mallCtr", "mallCtor"].includes(field);

const metricValue = (product: BusinessProductRecord, field: BusinessSortField): number | null => {
  const cardMap: Partial<Record<BusinessSortField, keyof BusinessCardMetrics>> = { cardGmv: "gmv", skuOrders: "skuOrders", units: "units", customers: "customers", aov: "aov", impressions: "impressions", clicks: "clicks", ctr: "ctr", addToCarts: "addToCarts", addToCartRate: "addToCartRate", ctor: "ctor", uniqueImpressions: "uniqueImpressions", uniqueClicks: "uniqueClicks", uniqueCtr: "uniqueCtr", addToCartUsers: "addToCartUsers", uniqueAddToCartRate: "uniqueAddToCartRate", uniqueCtor: "uniqueCtor" };
  const mallMap: Partial<Record<BusinessSortField, keyof BusinessMallMetrics>> = { mallImpressions: "impressions", mallClicks: "clicks", mallUniqueClicks: "uniqueClicks", mallCustomers: "customers", mallCtr: "ctr", mallCtor: "ctor", mallGmv: "gmv", mallUnits: "units" };
  return cardMap[field] ? product.card[cardMap[field]!] : mallMap[field] ? product.mall[mallMap[field]!] : null;
};

const formatMetric = (field: BusinessSortField, value: number | null) => field === "cardGmv" || field === "mallGmv" || field === "aov" ? amount(value) : isRate(field) ? rate(value) : count(value);
const inRange = (value: number | null, min: string, max: string) => { const lower = parseInput(min); const upper = parseInput(max); return (lower === null || (value !== null && value >= lower)) && (upper === null || (value !== null && value <= upper)); };
const hasFilters = (filters: BusinessProductFilters) => Object.values(filters).some((value) => value !== "" && value !== "all");

function RangeInput({ label, min, max, onMin, onMax }: { label: string; min: string; max: string; onMin: (value: string) => void; onMax: (value: string) => void }) {
  return <div className="filter-block"><label>{label}</label><div className="range-inputs"><input inputMode="decimal" value={min} onChange={(event) => onMin(event.target.value)} placeholder="最小值" /><span>至</span><input inputMode="decimal" value={max} onChange={(event) => onMax(event.target.value)} placeholder="最大值" /></div></div>;
}

function TrendChart({ points, selected, labels, value }: { points: Array<{ date: string; metrics: BusinessCardMetrics | BusinessMallMetrics }>; selected: readonly string[]; labels: Record<string, string>; value: (metrics: BusinessCardMetrics | BusinessMallMetrics, key: string) => number | null }) {
  const colors = ["#6659ee", "#36a57c"]; const width = 690; const height = 210; const padding = { x: 28, top: 18, bottom: 30 };
  const series = selected.map((key, index) => ({ key, color: colors[index], values: points.map((point) => value(point.metrics, key)) }));
  const segments = (values: Array<number | null>, index: number) => { const numbers = values.filter((item): item is number => item !== null); if (!numbers.length) return []; const min = Math.min(...numbers); const max = Math.max(...numbers); const scale = (item: number) => max === min ? height / 2 : padding.top + ((max - item) / (max - min)) * (height - padding.top - padding.bottom); const chunks: string[] = []; let chunk: string[] = []; values.forEach((item, pointIndex) => { if (item === null) { if (chunk.length) chunks.push(chunk.join(" ")); chunk = []; return; } const x = padding.x + pointIndex * ((width - padding.x * 2) / Math.max(values.length - 1, 1)); chunk.push(`${x},${scale(item)}`); }); if (chunk.length) chunks.push(chunk.join(" ")); return chunks; };
  if (!points.length) return <div className="business-chart-empty">没有可展示的每日趋势数据。</div>;
  return <div className="business-chart"><div className="business-chart-legend">{series.map((item) => <span key={item.key}><i style={{ background: item.color }} />{labels[item.key]}</span>)}<small>各指标按自身范围绘制；空值不连线</small></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="每日趋势图"><line x1={padding.x} x2={width - padding.x} y1={height - padding.bottom} y2={height - padding.bottom} className="business-chart-axis" />{series.flatMap((item) => segments(item.values, series.indexOf(item)).map((segment, index) => <polyline key={`${item.key}-${index}`} points={segment} fill="none" stroke={item.color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />))}{points.map((point, index) => <text key={point.date} x={padding.x + index * ((width - padding.x * 2) / Math.max(points.length - 1, 1))} y={height - 8} textAnchor="middle">{point.date.slice(5)}</text>)}</svg></div>;
}

function SortHeader({ field, sort, onSort }: { field: BusinessSortField; sort: { field: BusinessSortField | null; direction: SortDirection | null }; onSort: (field: BusinessSortField) => void }) {
  const active = sort.field === field;
  return <button className={`sort-button${active ? " active" : ""}`} onClick={() => onSort(field)}><span>{columnLabels[field]}</span>{active ? sort.direction === "desc" ? <ArrowDown size={14} /> : <ArrowUp size={14} /> : <ArrowUpDown size={14} />}</button>;
}

export default function BusinessAnalysis({ hidden = false }: { hidden?: boolean }) {
  const fileInputRef = useRef<HTMLInputElement>(null); const [state, setState] = usePersistedState<BusinessAnalysisState>("business-analysis", initialState); const [error, setError] = useState(""); const [pendingBatch, setPendingBatch] = useState<BusinessBatch | null>(null); const [loading, setLoading] = useState(false); const [dragging, setDragging] = useState(false);
  const batch = state.batches.find((item) => item.id === state.activeBatchId) ?? state.batches[0] ?? null; const columns = [...defaultColumns, ...state.visibleColumns];
  const statuses = useMemo(() => batch ? [...new Set(batch.products.map((product) => product.publishStatus).filter(Boolean))].sort() : [], [batch]);
  const products = useMemo(() => { if (!batch) return []; const filters = state.filters; const query = filters.search.trim().toLowerCase(); return [...batch.products].filter((product) => (!query || product.name.toLowerCase().includes(query) || product.productId.toLowerCase().includes(query)) && (filters.publishStatus === "all" || product.publishStatus === filters.publishStatus) && (filters.sales === "all" || filters.sales === "with-sales" ? (product.card.skuOrders ?? 0) > 0 : (product.card.skuOrders ?? 0) <= 0) && inRange(product.card.gmv, filters.cardGmvMin, filters.cardGmvMax) && inRange(product.card.impressions, filters.impressionsMin, filters.impressionsMax) && inRange(product.card.ctr, filters.ctrMin, filters.ctrMax) && inRange(product.card.addToCartRate, filters.addToCartRateMin, filters.addToCartRateMax) && inRange(product.card.ctor, filters.ctorMin, filters.ctorMax) && inRange(product.mall.impressions, filters.mallImpressionsMin, filters.mallImpressionsMax) && inRange(product.mall.ctr, filters.mallCtrMin, filters.mallCtrMax)).sort((left, right) => { if (!state.sort.field || !state.sort.direction) return left.originalIndex - right.originalIndex; const a = metricValue(left, state.sort.field) ?? Number.NEGATIVE_INFINITY; const b = metricValue(right, state.sort.field) ?? Number.NEGATIVE_INFINITY; return state.sort.direction === "desc" ? b - a : a - b; }); }, [batch, state.filters, state.sort]);
  const update = (patch: (current: BusinessAnalysisState) => BusinessAnalysisState) => setState((current) => patch(current));
  const updateFilter = <K extends keyof BusinessProductFilters>(key: K, value: BusinessProductFilters[K]) => update((current) => ({ ...current, filters: { ...current.filters, [key]: value } }));
  const commitBatch = (next: BusinessBatch, replace: boolean) => { update((current) => ({ ...current, batches: replace ? current.batches.map((item) => item.startDate === next.startDate && item.endDate === next.endDate ? next : item) : [...current.batches, next], activeBatchId: next.id })); setPendingBatch(null); };
  const importFiles = async (files: FileList | File[]) => { setError(""); setLoading(true); try { const next = await parseBusinessFiles(Array.from(files)); const duplicate = state.batches.some((item) => item.startDate === next.startDate && item.endDate === next.endDate); if (duplicate) setPendingBatch(next); else commitBatch(next, false); } catch (caught) { setError(caught instanceof Error ? caught.message : "文件解析失败，请检查三份 Excel。"); } finally { setLoading(false); if (fileInputRef.current) fileInputRef.current.value = ""; } };
  const toggleColumn = (field: BusinessSortField) => update((current) => ({ ...current, visibleColumns: current.visibleColumns.includes(field) ? current.visibleColumns.filter((item) => item !== field) : [...current.visibleColumns, field] }));
  const toggleTrendMetric = (kind: "card" | "mall", key: string) => update((current) => { const field = kind === "card" ? "cardTrendMetrics" : "mallTrendMetrics"; const selected = current[field] as string[]; if (selected.includes(key)) return { ...current, [field]: selected.filter((item) => item !== key) }; return selected.length >= 2 ? current : { ...current, [field]: [...selected, key] }; });
  const handleSort = (field: BusinessSortField) => update((current) => ({ ...current, sort: current.sort.field !== field ? { field, direction: "desc" } : current.sort.direction === "desc" ? { field, direction: "asc" } : { field: null, direction: null } }));
  const selectBatch = (id: string) => update((current) => ({ ...current, activeBatchId: id }));
  const selectTab = (activeTab: BusinessAnalysisState["activeTab"]) => update((current) => ({ ...current, activeTab }));
  return <main className="workspace business-workspace" hidden={hidden} aria-hidden={hidden}><section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> BUSINESS ANALYTICS</div><h1>经营分析</h1><p>只分析商品卡和商城页数据，其他来源不会进入本模块。</p></div><div className="privacy-note"><CheckCircle2 size={17} /> 文件仅在浏览器本地解析</div></section>
    {batch && <section className="business-batch-bar"><div className="board-switcher">{state.batches.map((item) => <button key={item.id} className={item.id === batch.id ? "active" : ""} onClick={() => selectBatch(item.id)}>{item.startDate} 至 {item.endDate}</button>)}</div></section>}
    {batch && <section className="source-bar business-source-bar"><div className="source-bar-main"><div className="source-bar-icon"><Store size={18} /></div><div className="source-file"><span>当前周期 · 三份官方数据源完整</span><strong>{batch.startDate} 至 {batch.endDate}</strong><small className="business-source-files" title={`${batch.sources.productData.fileName}\n${batch.sources.cardTraffic.fileName}\n${batch.sources.allTraffic.fileName}`}>商品数据：{batch.sources.productData.fileName} · 商品卡：{batch.sources.cardTraffic.fileName} · 全部：{batch.sources.allTraffic.fileName}</small></div><span className="source-divider" /><span className="source-product-count">{formatCount(batch.products.length)} 件商品</span></div><div className="source-bar-actions"><button className="compact-import-button" onClick={() => fileInputRef.current?.click()}><CloudUpload size={15} /> {loading ? "正在解析…" : "导入本期数据"}</button></div></section>}
    {!batch && <section className="import-card business-import-card"><div className="import-copy"><div className="section-icon"><FileSpreadsheet size={20} /></div><div><div className="section-kicker">本期数据</div><h2>一次导入三份 TikTok 官方 Excel</h2><p>商品数据、商品卡专项、全部流量；系统会根据文件内容自动识别。</p></div></div><div className={`dropzone${dragging ? " dragging" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); void importFiles(event.dataTransfer.files); }} onClick={() => fileInputRef.current?.click()} role="button" tabIndex={0}><CloudUpload size={19} /><span>{loading ? "正在解析三份文件…" : "拖入三份 Excel，或点击选择"}</span></div></section>}
    <input ref={fileInputRef} type="file" multiple accept=".xlsx,.xls" onChange={(event) => void importFiles(event.target.files ?? [])} hidden />
    {error && <div className="notice error-notice" role="alert"><AlertTriangle size={18} /><span>{error}</span><button onClick={() => setError("")} aria-label="关闭错误提示"><X size={16} /></button></div>}
    {pendingBatch && <div className="notice info-notice business-replace-notice"><AlertTriangle size={17} /><span>{pendingBatch.startDate} 至 {pendingBatch.endDate} 已有批次。是否用刚导入的三份文件替换？</span><button className="text-button" onClick={() => commitBatch(pendingBatch, true)}>替换该周期</button><button className="text-button" onClick={() => setPendingBatch(null)}>取消</button></div>}
    {batch && <><section className="business-tabs board-switcher"><button className={state.activeTab === "overview" ? "active" : ""} onClick={() => selectTab("overview")}>店铺概览</button><button className={state.activeTab === "products" ? "active" : ""} onClick={() => selectTab("products")}>商品表现</button></section>{state.activeTab === "overview" ? <>
      <section className="business-kpi-grid"><Kpi label="商品卡 GMV" value={amount(batch.shopCardSummary.gmv)} /><Kpi label="SKU订单" value={count(batch.shopCardSummary.skuOrders)} /><Kpi label="商品曝光" value={count(batch.shopCardSummary.impressions)} /><Kpi label="商品点击" value={count(batch.shopCardSummary.clicks)} /><Kpi label="CTR" value={rate(batch.shopCardSummary.ctr)} /><Kpi label="CTOR" value={rate(batch.shopCardSummary.ctor)} /></section>
      <section className="list-card business-chart-card"><div className="list-card-header"><div><div className="list-heading"><h2>商品卡趋势</h2><span className="result-pill">每日</span></div><p>最多选择两个指标进行走势比较。</p></div><MetricChoices options={cardTrendOptions} labels={cardTrendLabels} selected={state.cardTrendMetrics} onToggle={(key) => toggleTrendMetric("card", key)} /></div><TrendChart points={batch.shopCardTrend} selected={state.cardTrendMetrics} labels={cardTrendLabels} value={(metrics, key) => (metrics as BusinessCardMetrics)[key as keyof BusinessCardMetrics]} /></section>
      <section className="business-mall-section"><div className="business-section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> MALL PAGE</div><h2>商城页表现</h2></div><p>仅使用全部流量文件中的商城页字段。</p></div><section className="business-kpi-grid business-mall-kpis"><Kpi label="商城曝光" value={count(batch.shopMallSummary.impressions)} /><Kpi label="商城点击" value={count(batch.shopMallSummary.clicks)} /><Kpi label="商城CTR" value={rate(batch.shopMallSummary.ctr)} /><Kpi label="商城CTOR" value={rate(batch.shopMallSummary.ctor)} /><Kpi label="商城GMV" value={amount(batch.shopMallSummary.gmv)} /><Kpi label="商城成交件数" value={count(batch.shopMallSummary.units)} /></section><section className="list-card business-chart-card"><div className="list-card-header"><div><div className="list-heading"><h2>商城每日趋势</h2><span className="result-pill">每日</span></div></div><MetricChoices options={mallTrendOptions} labels={mallTrendLabels} selected={state.mallTrendMetrics} onToggle={(key) => toggleTrendMetric("mall", key)} /></div><TrendChart points={batch.shopMallTrend} selected={state.mallTrendMetrics} labels={mallTrendLabels} value={(metrics, key) => (metrics as BusinessMallMetrics)[key as keyof BusinessMallMetrics]} /></section></section>
      {batch.qualityIssues.length > 0 && <section className="business-quality"><div className="filter-title"><AlertTriangle size={17} /><strong>数据质量提示</strong></div>{batch.qualityIssues.map((issue, index) => <p key={`${issue.message}-${index}`}>{issue.message}</p>)}</section>}
    </> : <><section className="filter-card business-filter-card"><div className="filter-card-header"><div className="filter-title"><Filter size={17} /><strong>商品筛选</strong><span>{formatCount(products.length)} 个当前结果</span></div>{hasFilters(state.filters) && <button className="text-button" onClick={() => update((current) => ({ ...current, filters: defaultFilters() }))}><RefreshCw size={14} /> 清除筛选</button>}</div><div className="filter-grid business-filter-grid"><div className="filter-block search-filter"><label>商品名 / ID</label><div className="search-input"><Search size={15} /><input type="search" value={state.filters.search} onChange={(event) => updateFilter("search", event.target.value)} placeholder="搜索商品名或商品 ID" /></div></div><div className="filter-block"><label>发品状态</label><div className="select-wrap"><select value={state.filters.publishStatus} onChange={(event) => updateFilter("publishStatus", event.target.value)}><option value="all">不限</option>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select><ChevronDown size={15} /></div></div><div className="filter-block"><label>成交情况</label><div className="select-wrap"><select value={state.filters.sales} onChange={(event) => updateFilter("sales", event.target.value as BusinessProductFilters["sales"])}><option value="all">不限</option><option value="with-sales">有成交</option><option value="without-sales">无成交</option></select><ChevronDown size={15} /></div></div><RangeInput label="商品卡 GMV" min={state.filters.cardGmvMin} max={state.filters.cardGmvMax} onMin={(value) => updateFilter("cardGmvMin", value)} onMax={(value) => updateFilter("cardGmvMax", value)} /><RangeInput label="曝光" min={state.filters.impressionsMin} max={state.filters.impressionsMax} onMin={(value) => updateFilter("impressionsMin", value)} onMax={(value) => updateFilter("impressionsMax", value)} /><RangeInput label="CTR（%）" min={state.filters.ctrMin} max={state.filters.ctrMax} onMin={(value) => updateFilter("ctrMin", value)} onMax={(value) => updateFilter("ctrMax", value)} /><RangeInput label="加购率（%）" min={state.filters.addToCartRateMin} max={state.filters.addToCartRateMax} onMin={(value) => updateFilter("addToCartRateMin", value)} onMax={(value) => updateFilter("addToCartRateMax", value)} /><RangeInput label="CTOR（%）" min={state.filters.ctorMin} max={state.filters.ctorMax} onMin={(value) => updateFilter("ctorMin", value)} onMax={(value) => updateFilter("ctorMax", value)} /><RangeInput label="商城曝光" min={state.filters.mallImpressionsMin} max={state.filters.mallImpressionsMax} onMin={(value) => updateFilter("mallImpressionsMin", value)} onMax={(value) => updateFilter("mallImpressionsMax", value)} /><RangeInput label="商城CTR（%）" min={state.filters.mallCtrMin} max={state.filters.mallCtrMax} onMin={(value) => updateFilter("mallCtrMin", value)} onMax={(value) => updateFilter("mallCtrMax", value)} /></div></section>
      <section className="list-card business-products-card"><div className="list-card-header"><div><div className="list-heading"><h2>商品表现</h2><span className="result-pill">{formatCount(products.length)} 个结果</span></div><p>商品 ID 是跨周期的长期匹配主键。</p></div><details className="business-column-settings"><summary><Settings2 size={15} /> 指标设置</summary><div>{optionalColumns.map((field) => <label key={field}><input type="checkbox" checked={state.visibleColumns.includes(field)} onChange={() => toggleColumn(field)} /> {columnLabels[field]}</label>)}</div></details></div><div className="table-wrap"><table className="business-product-table" data-sort-field={state.sort.field ?? undefined}><thead><tr><th className="business-product-name">商品</th>{columns.map((field) => <th key={field} className={state.sort.field === field ? "business-active-sort" : ""}><SortHeader field={field} sort={state.sort} onSort={handleSort} /></th>)}</tr></thead><tbody>{products.map((product) => <tr key={product.productId}><td className="business-product-name"><strong title={product.name}>{product.name}</strong><small>ID：{product.productId}</small><em>{product.publishStatus || "未填写"}</em></td>{columns.map((field) => <td key={field} className={state.sort.field === field ? "business-active-sort" : ""}>{formatMetric(field, metricValue(product, field))}</td>)}</tr>)}</tbody></table>{!products.length && <div className="no-results"><PackageSearch size={20} /><strong>没有符合条件的商品</strong><span>尝试放宽筛选条件。</span></div>}</div></section></>}</>}
  </main>;
}

function Kpi({ label, value }: { label: string; value: string }) { return <div className="business-kpi"><span>{label}</span><strong>{value}</strong></div>; }
function MetricChoices({ options, labels, selected, onToggle }: { options: readonly string[]; labels: Record<string, string>; selected: readonly string[]; onToggle: (key: string) => void }) { return <div className="business-metric-choices">{options.map((key) => <button type="button" key={key} className={selected.includes(key) ? "active" : ""} onClick={() => onToggle(key)}>{labels[key]}</button>)}</div>; }
